/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n2.0-62840-g37ddcb27c6"
#endif /* AVUTIL_FFVERSION_H */
